Resources:
  SFTPUser2:
    Type: AWS::Transfer::User
    DependsOn:
      - SFTPUser2AccessRole
    Properties:
      UserName: sftp.user2
      ServerId: s-714daa9a61934c658
      HomeDirectoryType: LOGICAL
      HomeDirectoryMappings:
        - Entry: "/user2"
          Target: "/mastercard-${self:provider.stage}-sftp-data/user2"
      SshPublicKeys:
        - ${ssm:/mastercard-ingestion/integration/sftp/ssh/public_kpmg}
      Role: arn:aws:iam::712963084888:role/SFTPUser2AccessRole
      Tags:
        - Key: ENVIRONMENT
          Value: ${self:provider.stage}
        - Key: stack
          Value: ingestion

  SFTPUser2AccessRole:
    Type: AWS::IAM::Role
    Properties:
      Description: IAM role to allow KMPG access SFTP S3 bucket
      RoleName: SFTPUser2AccessRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
                - transfer.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: SFTPUser2AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Sid: 'DirectoryAccess'
                Action:
                  - 's3:*'
                Resource:
                  - 'arn:aws:s3:::mastercard-${self:provider.stage}-sftp-data'
                  - 'arn:aws:s3:::mastercard-${self:provider.stage}-sftp-data/user2/*'
                  - 'arn:aws:s3:::mastercard-${self:provider.stage}-sftp-data/public/*'
              - Effect: Allow
                Sid: 'UserFolderAccess'
                Action:
                  - 's3:*'
                Resource:
                  - 'arn:aws:s3:::mastercard-${self:provider.stage}-sftp-data/user2*'
                  - 'arn:aws:s3:::mastercard-${self:provider.stage}-sftp-data/public*'
      Tags:
        - Key: ENVIRONMENT
          Value: ${self:provider.stage}
        - Key: stack
          Value: ingestion
